### ISSUE TITLE
怎么使用micropython刷入程序

### ISSUE THREAD

**Issue by Lcy-131** [eggfly/AlphaPi#6]
怎么刷入.py文件到alphapi

**Comment by hyzx86** [comment]
参考 micropython 官网教程
推荐VSC插件：
https://marketplace.visualstudio.com/items?itemName=RT-Thread.rt-thread-micropython

**Comment by Lcy-131** [comment]
能不能让我加入这个项目

**Comment by Lcy-131** [comment]
我写了个esp-idf的示例

**Comment by hyzx86** [comment]
> 我写了个esp-idf的示例

给个建议
你可以fork这个仓库，添加你的示例，然后发起一个合并请求
再提加入仓库😁

**Comment by Lcy-131** [comment]
已经fork了，怎么做

**Comment by hyzx86** [comment]
在你的仓库中新建一个分支，添加你的代码，
然后推送到github ，刷新本仓库pro 页面，你会看到create pull request

**Comment by Lcy-131** [comment]
像这样就好了是吧
